### ISSUE TITLE
Problem with adding recipes

### ISSUE THREAD

**Issue by Shade-Jonezy** [thebrightspark/S.T.E.M#16]
Not every recipe I add registers in the recipe scanner and some register the wrong items, like flux block from Thermal Expansion.  However, the recipes aren't affecting modded items, but also are affecting Minecraft's own items.

**Comment by thebrightspark** [comment]
You're going to need to supply a bit more info and be more specific please. Can you give a specific example of one that doesn't work? And how do you add the recipe? Can you also post your JSON file?

**Comment by Shade-Jonezy** [comment]
Your mod makes recipes in a CSV Format, not JSON.  So do you want the CSV File?

**Comment by Shade-Jonezy** [comment]
Four examples of added recipes to the "Recipes.CSV" File that don't register in game are as followed:
Magmatic Generator - Extra Utilities
Advanced Ender Generator - Exponential Power
Ender Cell - Exponential Power
Iron Ingot - Minecraft

**Comment by thebrightspark** [comment]
Oh yes sorry! Been a while since I've done much with this mod. But yes, the CSV.

**Comment by Shade-Jonezy** [comment]
Okay I'll attach it.  Maybe you can see what's going on.  I had to pack it in a zip in order to post it.
[recipes.zip](https://github.com/thebrightspark/S.T.E.M/files/2338404/recipes.zip)

**Comment by Shade-Jonezy** [comment]
Guess the issue is a tough one.  Take your time okay.  I do like the concept of this mod and the adding of recipes through a CSV File Format makes adding recipes way easier than most item duplication mods out there.  Please have a wonderful night okay and take care.

**Comment by thebrightspark** [comment]
I managed to reproduce this, but then once I tried in my development environment after updating Forge, I couldn't reproduce it...
So I've released v0.1.5 with the updated Forge. Let me know if you're still having issues with that version.

**Comment by Shade-Jonezy** [comment]
I used the most recent Forge (9/4/18) and I doubt it is usable as that Forge Version crashes no matter what with any mod.  However, when I go one version below that and add S. T. E. M. the mod gets removed during the boot up procedure of Minecraft even though it was added correctly.  Don't know why it does that, but with this error going on I can't test your mod.  It doesn't happen to any of the other mods I add to my pack just this recent version of S. T. E. M.  I'm sorry to trouble you Thebrightspark.  No error report so I am stumped as to why it isn't showing up in game in the mods section.

**Comment by thebrightspark** [comment]
Hmm weird.
Can you please try using Forge 14.23.4.2705?
And can you tell me the exact versions you've been trying and what happened?

**Comment by Shade-Jonezy** [comment]
The versions I used were 14.23.4.2759 and the one that crashed no matter what mod was added, which is completely useless for testing, was 14.23.4.2760.  Using 14.23.4.2759, like I said I add the mod like any other mod, add to mod folder, and when the game fully loads the mod has been removed.  How you can tell is the number of mods doesn't change on the main menu and the mod doesn't appear in the mods list when clicking the mods button on the main menu.  To be honest there isn't much left I can explain as this pretty much is as much detail I can actually give on the topic.

**Comment by thebrightspark** [comment]
And did you try the Forge version I said? That is the latest recommend Forge version (which I recently updatedy mod to use).

Can you also post your latest logs when this happens? I've never heard of a mod disappearing... But if it happened for a reason then it should say why in the logs.

**Comment by Shade-Jonezy** [comment]
This latest log, not crash as the game never crashed, seems to show the reason for the mod not showing up.  I used the find function to find it in the text file and it seems it reads no mod in the jar if I read correctly.  Then another instance of it being mentioned is that whatever it could find was added elsewhere instead of a mod it reads it was added to the class files.  Weird, right?  This was all I could dig up from the current files.  You are free to read it and see for yourself.

[latest.log](https://github.com/thebrightspark/S.T.E.M/files/2355082/latest.log)

**Comment by thebrightspark** [comment]
Okay, I see the error as to why it's not loading:
```
[00:51:21] [main/WARN] [FML]: Zip file stem-1.12.2-0.1.5.jar failed to read properly, it will be ignored
java.lang.RuntimeException: Empty reference 
	at net.minecraftforge.fml.common.versioning.VersionParser.parseVersionReference(VersionParser.java:49) ~[VersionParser.class:?]
	at net.minecraftforge.fml.common.MetadataCollection$ArtifactVersionAdapter.read(MetadataCollection.java:123) ~[MetadataCollection$ArtifactVersionAdapter.class:?]
	at net.minecraftforge.fml.common.MetadataCollection$ArtifactVersionAdapter.read(MetadataCollection.java:111) ~[MetadataCollection$ArtifactVersionAdapter.class:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[TypeAdapterRuntimeTypeWrapper.class:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) ~[CollectionTypeAdapterFactory$Adapter.class:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[CollectionTypeAdapterFactory$Adapter.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[ReflectiveTypeAdapterFactory$1.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[ReflectiveTypeAdapterFactory$Adapter.class:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[TypeAdapterRuntimeTypeWrapper.class:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[ArrayTypeAdapter.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[ReflectiveTypeAdapterFactory$1.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[ReflectiveTypeAdapterFactory$Adapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:925) ~[Gson.class:?]
	at net.minecraftforge.fml.common.MetadataCollection.from(MetadataCollection.java:77) ~[MetadataCollection.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:65) [JarDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:47) [ContainerType.class:?]
	at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:74) [ModCandidate.class:?]
	at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:93) [ModDiscoverer.class:?]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:425) [Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:566) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.init(Minecraft.java:466) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3929) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[00:51:21] [main/WARN] [FML]: Mod vanillafix is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.0.9-97
```
Looks like the "modListVersion" in my mcmod.info is missing or the value is empty... which is false because it exists in the mod. So either you've downloaded the mod from somewhere dodgy or something's edited it for some unknown reason. Or something else... I have no idea. Point is, it should be fine.

Try re-downloading the mod from CurseForge and try again.

**Comment by Shade-Jonezy** [comment]
I'll give it a shot, but the thing is I downloaded it from CurseForge.  I will update you on the outcome.

**Comment by Shade-Jonezy** [comment]
Sorry to inform you it does the same thing even after redownloading it from CurseForge.  Something in the mod itself is doing it.  The past versions loaded up fine.  So I know it can't be user error.  Let me know if something comes up.  Also, I must inform you that I do use launcher called, "MultiMC" for the purpose of multiple modpacks and easy mod, Forge and Liteloader adding tool.

**Comment by thebrightspark** [comment]
Well I already was testing the latest version of my mod fine alongside some of the mods you're using. I use the Twitch client for that, and it never does anything funny because it uses the vanilla launcher. Maybe try that and see if it's any different?

**Comment by thebrightspark** [comment]
Actually, I take it back! I just checked and I was testing with 0.1.4. Tried just now with 0.1.5 and I get the same error. I'll try find out what's going on... might just be a dodgy build or something.

**Comment by thebrightspark** [comment]
Alright I've fixed that mistake now... 0.1.6 will work once you can get your hands on it

**Comment by Shade-Jonezy** [comment]
That it does thebrightspark.  The mod is being registered fine and it has set up a folder in the configuration folder with the usual contents you would normally see.  Now is my turn as soon as I find out what is causing a fatal crash on my end.  From what I read in my report I should be able to fix the crash by removing a particular mod.  So once I'm set up and running I can properly test your mod.  I thank you for your hard work and appreciate you being cool with all these posts.  Have a great weekend alright.

**Comment by Shade-Jonezy** [comment]
The mod has seen improvements, however it still refuses to scan some recipe items even when added to the "Recipes.CSV".  Two such items are granite and either andesite or diorite.  It recognized the polished versions just not the original blocks.  I enjoy using this mod though you do a marvelous job with this mod and I must say I am indeed impressed.  Also, to clarify I am not kissing ass, I merely believe people deserve compliments where due.

**Comment by thebrightspark** [comment]
Thanks :)
Can you share your entries in the recipes CSV for those blocks? And can you also post your latest logs?

**Comment by Shade-Jonezy** [comment]
[Requested Files.zip](https://github.com/thebrightspark/S.T.E.M/files/2364684/Requested.Files.zip)

Above are the CSV for the recipes, not much has changed except items with unable to be scanned by the Matter Scanner have changed regardless of being included in the Recipes.CSV, and the Latest.log.  The notable changes were that podzol became unscannable and the Scanner Storage Block became unscannable to name two items.  I'm unsure why all items aren't scannable when added to the CSV File.  All I do know about the CSV File is that despite keeping the data always loads with just one column and requires you to add the two remaining columns just to add the additional items to it.  However, I don't think that could be the issue unless you think it loading that way is.  Like I said it keeps the information when adding the columns back.

**Comment by Shade-Jonezy** [comment]
Please take your time okay.  I'm not in a hurry okay.  I just like testing great mods,
like yours.  However, we all have lives outside of gaming and modding so don't
worry about doing anything so soon okay.  I'll wait as long as I have to so have a great night/day okay.

**Comment by Shade-Jonezy** [comment]
Sorry for all the "okay" ending the sentences in my previous comment.  Never caught it until now.  Take care and have a wonderful week.

**Comment by thebrightspark** [comment]
Hey sorry, was out of the country for a week hence why I haven't replied in a while.
I just tried with all of the items you mentioned, and I can scan them fine using the recipes you provided... so I don't know what's wrong.
It's worth mentioning that I'm not using all of the same mods as you are, but if you're able to provide a Twitch mod pack export then I can install the exact same mods as you and try again.
